<?php

namespace GestionBundle\Entity\finanzas;

/**
 * AcreditacionSubsidioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcreditacionSubsidioRepository extends \Doctrine\ORM\EntityRepository
{

	public function existeAcreditacion($importe, $fecha)
	{
        $query = $this->getEntityManager()
                      ->createQuery('SELECT p 
                                     FROM GestionBundle:finanzas\AcreditacionSubsidio p
                                     WHERE p.fecha = :fecha AND p.importe = :importe')
                      ->setParameter('fecha', $fecha)
                      ->setParameter('importe', $importe);                      
        return $query->getOneOrNullResult();			
	}		

  public function getAcreditaciones()
  {
        $query = $this->getEntityManager()
                      ->createQuery('SELECT p 
                                     FROM GestionBundle:finanzas\AcreditacionSubsidio p
                                     ORDER BY p.fecha');                   
        return $query->getResult();      
  }     
}
