<?php

namespace GestionBundle\Entity\finanzas;

/**
 * PagoSubsidioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoSubsidioRepository extends \Doctrine\ORM\EntityRepository
{

	public function getPagoSubsidio($concepto, $mes, $anio)
	{
        $query = $this->getEntityManager()
                      ->createQuery('SELECT p 
                                     FROM GestionBundle:finanzas\PagoSubsidio p
                                     WHERE p.concepto = :concepto AND p.periodoMes = :mes AND p.periodoAnio = :anio')
                      ->setParameter('concepto', $concepto)
                      ->setParameter('mes', $mes)
                      ->setParameter('anio', $anio);
        return $query->getOneOrNullResult();			
	}

	public function pagosPendientesDeAcreditar()
	{
        $query = $this->getEntityManager()
                      ->createQuery('SELECT p 
                                     FROM GestionBundle:finanzas\PagoSubsidio p
                                     WHERE p.percibido = :percibido
                                     ORDER BY p.periodoAnio, p.periodoMes')
                      ->setParameter('percibido', false);
        return $query->getResult();			
	}	
}
