<?php

namespace GestionBundle\Entity\taller;

/**
 * AnomaliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnomaliaRepository extends \Doctrine\ORM\EntityRepository
{

	public function getAnomaliasPendientes()
	{
        $query = $this->getEntityManager()
                      ->createQuery('SELECT a
                                     FROM GestionBundle:taller\Anomalia a 
                                     WHERE (a.diagramada = :diagramada) AND (a.reparada = :reparada)')
                      ->setParameter('diagramada', false)
                      ->setParameter('reparada', false);
        return $query->getResult();			
	}		

  public function getAnomalias()
  {
        $query = $this->getEntityManager()
                      ->createQuery('SELECT a
                                     FROM GestionBundle:taller\Anomalia a 
                                     ORDER BY a.fecha');
        return $query->getResult();     
  }     
}
