<?php

namespace GestionBundle\Entity\taller;

/**
 * AnomaliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagramaTareaRepository extends \Doctrine\ORM\EntityRepository
{

	public function getDiagramaTareaPendiente($responsable, $fecha)
	{
        $query = $this->getEntityManager()
                      ->createQuery('SELECT dt
                                     FROM GestionBundle:taller\DiagramaTarea dt 
                                     WHERE (dt.responsable = :responsable)')
                      ->setParameter('responsable', $responsable);                    
        return $query->getResult();			
	}		   
}
