<?php

namespace GestionBundle\Entity\taller;

/**
 * PlanillaRecepcionAnomaliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanillaRecepcionAnomaliaRepository extends \Doctrine\ORM\EntityRepository
{

	public function getListaNovedadActiva()
	{
        $query = $this->getEntityManager()
                      ->createQuery('SELECT l 
                                     FROM GestionBundle:taller\ListaNovedadPlanilla l 
                                     WHERE l.activa= :activo')
                      ->setParameter('activo', true);
        return $query->getOneOrNullResult();			
	}	

	public function getPlanillaNovedad($f0015)
	{
        $query = $this->getEntityManager()
                      ->createQuery('SELECT l 
                                     FROM GestionBundle:taller\PlanillaRecepcionAnomalia l 
                                     WHERE l.numeroF0015= :f0015')
                      ->setParameter('f0015', $f0015);
        return $query->getOneOrNullResult();			
	}		
}
