<?php

namespace GestionBundle\Entity\personal;

/**
 * ConductorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ConductorRepository extends \Doctrine\ORM\EntityRepository
{


}
