<?php

namespace GestionBundle\Entity;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends \Doctrine\ORM\EntityRepository
{

    public function listadoArticulos()
    {
        $query = $this->getEntityManager()
                      ->createQuery('SELECT a
                                     FROM GestionBundle:Articulo a 
                                     ORDER BY a.descripcion');
        return $query->getResult();            
    }    

}
